# Generated by Django 5.2 on 2026-03-03 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('did_exercise', models.BooleanField(default=False)),
                ('exercise_type', models.CharField(blank=True, max_length=50, null=True)),
                ('exercise_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daily_record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='account.dailyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very Low Mood'), (2, 'Low Mood'), (3, 'Neutral'), (4, 'Good Mood'), (5, 'Very Good Mood')])),
                ('stress_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very High Stress'), (2, 'High Stress'), (3, 'Moderate Stress'), (4, 'Low Stress'), (5, 'Very Low Stress')])),
                ('anxiety_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very High Anxiety'), (2, 'High Anxiety'), (3, 'Moderate Anxiety'), (4, 'Low Anxiety'), (5, 'Very Low Anxiety')])),
                ('note_text', models.TextField(blank=True, null=True)),
                ('daily_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.dailyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('sleep_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('abandoned', 'Abandoned')], default='open', max_length=20)),
                ('sleep_time', models.DateTimeField()),
                ('wake_time', models.DateTimeField(blank=True, null=True)),
                ('sleep_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='account.dailyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='WorkStudyRecord',
            fields=[
                ('workstudy_id', models.AutoField(primary_key=True, serialize=False)),
                ('workstudy_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('daily_record', models.OneToOneField(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='account.dailyrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('user', 'record_date'), name='unique_user_per_day'),
        ),
        migrations.AddIndex(
            model_name='sleeprecord',
            index=models.Index(fields=['status'], name='account_sle_status_9dcf2e_idx'),
        ),
        migrations.AddIndex(
            model_name='sleeprecord',
            index=models.Index(fields=['sleep_time'], name='account_sle_sleep_t_29484e_idx'),
        ),
    ]
