# Generated by Django 5.2 on 2026-03-03 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_dailyrecord_exerciserecord_moodrecord_sleeprecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciserecord',
            name='daily_record',
            field=models.OneToOneField(db_column='daily_record', on_delete=django.db.models.deletion.CASCADE, to='account.dailyrecord'),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='daily_record',
            field=models.OneToOneField(db_column='daily_record', on_delete=django.db.models.deletion.CASCADE, to='account.dailyrecord'),
        ),
        migrations.AlterField(
            model_name='workstudyrecord',
            name='daily_record',
            field=models.OneToOneField(db_column='daily_record', on_delete=django.db.models.deletion.CASCADE, to='account.dailyrecord'),
        ),
    ]
